fix: ssh 참조 위치 변경
BetterwaySystems/easy-deploy-manager-cli pull request #18
Opened 2022-10-17 04:59 UTC by khxxjxx

2022-10-17 05:45 UTC, Irelander requested changes
리뷰 내용 확인부탁드립니다 ! 

1. config도 지금 빈걸루 되어 있눈데 인자값으로 받아서 처리될수 있도록 하면 좋을것 같습니다 !

2022-10-17 05:45 UTC, Irelander commented on src/modules/installNode.ts
> +  );
1. exec 에 인자값의 내용이 길어 command 변수로 선언해서 사용하면 더 좋을것 같습니다. 

2. `find $HOME/.nvm ...` 을 통해서 찾는것보다 `which nvm` 을 통해서 nvm 커맨드가 실행가능한지 확인하는건 어떨까요 ? 
이유는 nvm 설치를 다른 디렉토리에 할수도 있어서 해당 명령어를 통해 확인하게 되면 다른 폴더에 설치 되어 있어도 설치가 되지 않았다고 판단하고 설치를 할수도 있어서 nvm 을 사용할수 있는지 없는지 ( 커맨드 사용이 가능한지 ) 를 확인하는게 더 좋을것 같습니다 !

2022-10-17 05:45 UTC, Irelander commented on src/modules/installNode.ts
> +  const hasNvm = checkNvmInstalled.stdout;
왘ㅋㅋㅋㅋㅋㅋㅋ 리턴하는 형태가 바뀌어서 stdout 객체는 전달되지 않습니더 ㅠ

2022-10-17 08:23 UTC, khxxjxx commented on src/modules/installNode.ts
> +  const hasNvm = checkNvmInstalled.stdout;
이럴수가...!

2022-10-18 06:12 UTC, Irelander requested changes
@khxxjxx 

요건은 오전 회의대로 RemoteServer ( SSH ) 의 property로 변경하는 작업 부탁드립니다. !

2022-10-20 01:38 UTC, merged